# hyprland.conf — main entry point
# https://wiki.hypr.land/Configuring/

################
### MONITORS ###
################

monitor = , preferred, auto, auto


####################
### GLOBAL VARS  ###
####################

$terminal    = kitty
$fileManager = nautilus
$menu        = wofi --show drun

xwayland = true


###############
### MODULES ###
###############

source = ~/.config/hypr/conf_hyprland/env.conf
source = ~/.config/hypr/conf_hyprland/autostart.conf
source = ~/.config/hypr/conf_hyprland/look-and-feel.conf
source = ~/.config/hypr/conf_hyprland/input.conf
source = ~/.config/hypr/conf_hyprland/keybinds.conf
source = ~/.config/hypr/conf_hyprland/windowrules.conf
