 #set the default wallpaper(s) seen on initial workspace(s) --depending on the number of monitors used

preload = /home/kvn/Imágenes/Fondos/sushi.jpg

splash = true

wallpaper {
  monitor = eDP-1
  path = /home/kvn/Imágenes/Fondos/sushi.jpg
  fit_mode = cover
  #timeout = 30
}

 
